<style type="text/css">
    #nuevoCliente{
        display: none;
    }
</style> 
<?php
    //print_r($this->clientes);
    //echo $idCliente=$this->clientes[0]['Id_cliente'];
?>
<script type="text/javascript">
    sessionStorage.setItem("id",<?php echo $this->clientes[0]['Id_cliente']?>);
      sessionStorage.setItem('accionCambiosDir',0);
</script>
<script type="text/javascript">
    $(document).ready(function(){
        $("#nuevo").hide();
      

    });
</script>
<script>
$(function(){
$(".checkbox-group li").bind("click", function(){

if($(this).hasClass("checkbox-group-active"))
{
$(this).removeClass("checkbox-group-active");
$(this).attr("value", "off");

}
else
{
$(this).addClass("checkbox-group-active");
$(this).attr("value", "on");

}

$("#checkbox-value").html("");
$(".checkbox-group li").each(function(){
//$("#checkbox-value").append($(this).text() + ":" + $(this).attr("value") + "");
if($(this).attr("value")=='on'){
   if($(".checkbox-group li").attr("id")=="btnEditarContacto"){
    alert("hola");

   }
$("#formDirecciones input").attr("disabled", false);
$("#formDirecciones select").attr("disabled", false);
$("#fornuevocontacto input").attr("disabled", false);
$("#fornuevocontacto select").attr("disabled", false);
$("#formMaquinas input").attr("disabled", false);
$("#formMaquinas select").attr("disabled", false);
      $("#nota").attr("disabled", false);

   
               
}else{
   $("#formDirecciones input").attr("disabled", true);
   $("#formDirecciones select").attr("disabled", true);
    $("#fornuevocontacto input").attr("disabled", true);
    $("#fornuevocontacto select").attr("disabled", true);
    $("#formMaquinas input").attr("disabled", true);
    $("#formMaquinas select").attr("disabled", true);
      $("#nota").attr("disabled", true);
   
  
}

});
});
});
</script>
<div class="col-xs-12">
    <form  name="clientesG" id="clientesG" class="form-inline" method="POST">
        <div class="form-group col-sm-4 col-lg-3">
            <label class="control-label col-md-5" for="tip">Tipo Cliente:</label>
            <div class="col-md-7">
                <select id="tipo" class="form-control" name="tipo" required>
                    <option>Seleccionar...</option>
                     <option value="10" <?php echo $selected=(@$this->clientes[0]['Id_tipocliente']==10)? 'selected':''; ?>>Crédito</option>
                    <option value="11" <?php echo $selected=(@$this->clientes[0]['Id_tipocliente']==11)? 'selected':''; ?>>Contado</option>
                     <option value="12" <?php echo $selected=(@$this->clientes[0]['Id_tipocliente']==12)? 'selected':''; ?>>Suspendido</option>
                </select>
            </div>
        </div>
        <div class="form-group col-sm-4 col-lg-3">
            <label class="control-label col-md-5" for="estatus">Estatus:</label>
            <div class="col-md-7">
                <select id="estatus" class="form-control" name="estatus" required>
                    <option>Seleccionar...</option>
                    <option value='10' <?php echo $selected=(@$this->clientes[0]['Id_estatus']==10)? 'selected':''; ?>>ACTIVO</option>
                    <option value="20" <?php echo $selected=(@$this->clientes[0]['Id_estatus']==20)? 'selected':''; ?>>INACTIVO</option>
                </select>
            </div>
        </div>
        <div class="form-group col-sm-4 col-lg-3">
            <label class="control-label col-md-5" for="nombre">Nombre</label>
            <div class="col-md-7">
                <input id="nombre" class="form-control" name="nombre" type="nombre" value="<?php echo @$this->clientes[0]['Nombre'];?>" required>
            </div>
        </div>
        <div class="form-group col-sm-4 col-lg-3">
            <label class="control-label col-md-5" for="rfc">RFC</label>
            <div class="col-md-7">
                <input id="rfc" class="form-control" name="rfc" type="text" value="<?php echo @$this->clientes[0]['RFC'];?>" required>
            </div>
        </div>
        <div class="form-group col-sm-4 col-lg-3">
            <label class="control-label col-md-5" for="tel1">Teléfono 1</label>
            <div class="col-md-7">
                <input id="tel1" class="form-control" name="tel1" type="text" value="<?php echo @$this->clientes[0]['Telefono1'];?>">
            </div>
        </div>
        <div class="form-group col-sm-4 col-lg-3">
            <label class="control-label col-md-5" for="tel2">Teléfono 2</label>
            <div class="col-md-7">
                <input id="tel2" class="form-control" name="tel2" type="text" value="<?php echo @$this->clientes[0]['Telefono2'];?>">
            </div>
        </div>
        <div class="form-group col-sm-4 col-lg-3">
            <label class="control-label col-md-5" for="fax">Fax</label>
            <div class="col-md-7">
                <input id="fax" class="form-control" name="fax" type="text" value="<?php echo @$this->clientes[0]['Fax'];?>">
            </div>
        </div>
        <div class="form-group col-sm-4 col-lg-3">
            <label class="control-label col-md-5" for="correo">Correo</label>
            <div class="col-md-7">
                <input id="correo" class="form-control" name="correo" type="email" value="<?php echo @$this->clientes[0]['Correo'];?>">
            </div>
        </div>
        <div class="form-group col-sm-4 col-lg-3">
            <label class="control-label col-md-5" for="web">Web</label>
            <div class="col-md-7">
                <input id="web" class="form-control" name="web" type="text" value="<?php echo @$this->clientes[0]['Web'];?>">
            </div>
        </div>
        <br/>
        <!--button class="btn btn-primary" type="submit">Guardar Clientes</button>
        <button id="cancelaCliente" class="btn btn-primary">Cancelar</button-->
    </form>
<div id="dialog-contacto" title="Nuevo Contacto :: <?php echo @$this->clientes[0]['Nombre'];?>">
    <div id="fornuevocontacto">
        <ul class="checkbox-group" id="btnEditarContacto">
                <li value="off"><span class="glyphicon glyphicon-pencil"></span>Editar</li>
             </ul>
        <form  name="contactosG" id="contactosG" method="POST" class="form-inline">
            <input type="hidden" name="idC" id='idC'/>
            <input type="hidden" id='identificadorContactos'/>
            <input type="hidden" name="idContacto" id="idContacto"/>
            <div class="form-group col-sm-4 col-lg-3">
                <label class="control-label col-md-5" for="tipC">Tipo Contacto:</label>
                <div class="col-md-7">
                    <select class="form-control" id="tipoContacto" name="tipoContacto">
                        <option>Seleccionar...</option>
                  <?php 
                    foreach ($this->datos as $option) {
                      echo " <option value='".$option['Id_tipocontacto']."'>".$option['Descripcion']."</option>";
                    }



                  ?>
                    </select>
                </div>
            </div>
            <div class="form-group col-sm-4 col-lg-3">
                <label class="control-label col-md-5" for="estatus">Estatus:</label>
                <div class="col-md-7">
                    <select class="form-control" id="estatusC" name="estatusC">
                        <option>Seleccionar...</option>
                        <option value='10'>ACTIVO</option>
                        <option value="20">INACTIVO</option>
                    </select>
                </div>
            </div>
            <div class="form-group col-sm-4 col-lg-3">
                <label class="control-label col-md-5" for="nombre">Nombre</label>
                <div class="col-md-7">
                    <input type="text" class="form-control" id="nombreC" name="nombreC" required>
                </div>
            </div>
            <div class="form-group col-sm-4 col-lg-3">
                <label class="control-label col-md-5" for="apellidos">Apellidos</label>
                <div class="col-md-7">
                    <input type="text" class="form-control" id="apellidosC" name="apellidosC" required>
                </div>
            </div>
            <div class="form-group col-sm-4 col-lg-3">
                <label class="control-label col-md-5" for="puesto">Puesto</label>
                <div class="col-md-7">
                    <input type="text" class="form-control" id="puestoC" name="puestoC">
                </div>
            </div>
            <div class="form-group col-sm-4 col-lg-3">
                <label class="control-label col-md-5" for="tel1">Teléfono 1</label>
                <div class="col-md-7">
                    <input type="text" class="form-control" id="tel1C" name="tel1C">
                </div>
            </div>
            <div class="form-group col-sm-4 col-lg-3">
                <label class="control-label col-md-5" for="exten1">Extensión 1</label>
                <div class="col-md-7">
                    <input type="text" class="form-control" id="exten1" name="exten1">
                </div>
            </div>
            <div class="form-group col-sm-4 col-lg-3">
                <label class="control-label col-md-5" for="tel2">Teléfono 2</label>
                <div class="col-md-7">
                    <input type="text" class="form-control" id="tel2C" name="tel2C">
                </div>
            </div>
            <div class="form-group col-sm-4 col-lg-3">
                <label class="control-label col-md-5" for="exten2">Extensión 2</label>
                <div class="col-md-7">
                    <input type="text" class="form-control" id="exten2" name="exten2">
                </div>
            </div>
            <div class="form-group col-sm-4 col-lg-3">
                <label class="control-label col-md-5" for="celular">Celular</label>
                <div class="col-md-7">
                    <input type="text" class="form-control" id="celular" name="celular">
                </div>
            </div>
            <div class="form-group col-sm-4 col-lg-3">
                <label class="control-label col-md-5" for="correo">Correo</label>
                <div class="col-md-7">
                    <input type="text" class="form-control" id="correoC" name="correoC">
                </div>
            </div>
            <div class="form-group col-sm-4 col-lg-3">
                <label class="control-label col-md-5" for="face">Facebook</label>
                <div class="col-md-7">
                    <input type="text" class="form-control" id="face" name="face">
                </div>
            </div>
            <div class="form-group col-sm-4 col-lg-3">
                <label class="control-label col-md-5" for="tw">Twitter</label>
                <div class="col-md-7">
                    <input type="text" class="form-control" id="tw" name="tw">
                </div>
            </div>
            <div class="form-group col-sm-4 col-lg-3">
                <label class="control-label col-md-5" for="syk">Skype</label>
                <div class="col-md-7">
                    <input type="text" class="form-control" id="sky" name="sky">
                </div>
            </div>
            <div class="form-group col-sm-4 col-lg-3">
                <label class="control-label col-md-5" for="fechaN">Fecha de Nacimiento</label>
                <div class="col-md-7">
                    <input type="date" class="form-control" id="fechaN" name="fechaN">
                </div>
            </div>
            <button type="submit" class="btn btn-primary" id="guardarConta">Guardar Contactos</button>
        </form>
    </div>
      </div>
<div id="dialog-direcciones" title="Nueva Dirección :: <?php echo @$this->clientes[0]['Nombre'];?>">
    <div id="formDirecciones">
           
            <ul class="checkbox-group" id="btnEditarDireccion">
                <li value="off"><span class="glyphicon glyphicon-pencil"></span>Editar</li>
             </ul>
        <form  name="contactosD" id="contactosD" method="POST" class="form-inline">
            <input type="hidden" name="idClienteDir" id='idClienteDir'></input>
            <input type="hidden" name="Id_direccion" id='Id_direccion'></input>
            <input type="hidden" id='identificadorDirecciones'>
            <div class="form-group col-sm-4 col-lg-3">
                <label class="control-label col-md-5" for="tipD">Tipo Dirección:</label>
                <div class="col-md-7">
                    <select class="form-control" id="tipoDireccion" name="tipoDireccion">
                           <option>Seleccionar...</option>
                  <?php 
                    foreach ($this->tiposDir as $option) {
                      echo " <option value='".$option['Id_tipodireccion']."'>".$option['Descripcion']."</option>";
                    }



                  ?>
                    </select>
                </div>
            </div>
            <div class="form-group col-sm-4 col-lg-3">
                <label class="control-label col-md-5" for="estatus">Estatus:</label>
                <div class="col-md-7">
                    <select class="form-control" id="estatusD" name="estatusD">
                        <option>Seleccionar...</option>
                        <option value='10'>ACTIVO</option>
                        <option value="20">INACTIVO</option>
                    </select>
                </div>
            </div>
            <div class="form-group col-sm-4 col-lg-3">
                <label class="control-label col-md-5" for="calle">Calle</label>
                <div class="col-md-7">
                    <input type="text" class="form-control" id="calle" name="calle" required>
                </div>
            </div>
            <div class="form-group col-sm-4 col-lg-3">
                <label class="control-label col-md-5" for="colonia">Colonia</label>
                <div class="col-md-7">
                    <input type="text" class="form-control" id="colonia" name="colonia" required>
                </div>
            </div>
            <div class="form-group col-sm-4 col-lg-3">
                <label class="control-label col-md-5" for="ciudad">Ciudad</label>
                <div class="col-md-7">
                    <input type="text" class="form-control" id="ciudad" name="ciudad">
                </div>
            </div>
            <div class="form-group col-sm-4 col-lg-3">
                <label class="control-label col-md-5" for="muni">Municipio</label>
                <div class="col-md-7">
                    <input type="text" class="form-control" id="muni" name="muni">
                </div>
            </div>
            <div class="form-group col-sm-4 col-lg-3">
                <label class="control-label col-md-5" for="estado">Estado</label>
                <div class="col-md-7">
                    <input type="text" class="form-control" id="estado" name="estado">
                </div>
            </div>
            <div class="form-group col-sm-4 col-lg-3">
                <label class="control-label col-md-5" for="cp">CP</label>
                <div class="col-md-7">
                    <input type="text" class="form-control" id="cp" name="cp">
                </div>
            </div>
            <div class="form-group col-sm-4 col-lg-3">
                <label class="control-label col-md-5" for="nota">Nota:</label>
                <div class="col-md-7">
                    <textarea class="form-control" rows="5" id="nota" name="nota"></textarea>
                </div>
            </div>
            <button type="submit" class="btn btn-primary" id="guardaDir">Guardar Dirección</button>
        </form>
    </div>
</div>
<div id="dialog-maquinas" title="Nueva Máquina :: <?php echo @$this->clientes[0]['Nombre'];?>">
    <div id='formMaquinas'>
      <ul class="checkbox-group" id="btnEditarMaquina">
                <li value="off"><span class="glyphicon glyphicon-pencil"></span>Editar</li>
             </ul>
            <form  name="clienteMaquina" id="clienteMaquina" method="POST" class="form-inline">
            <input type="hidden" name="idM" id='idM'/>
            <input type="hidden" id='identificadorMaquinas'/>
            <div class="form-group col-sm-4 col-lg-3">
                <label class="control-label col-md-5" for="descM">Descripcion</label>
                <div class="col-md-7">
                    <input type="text" class="form-control" id="descripcionM" name="descripcionM" required>
                </div>
            </div>
            <div class="form-group col-sm-4 col-lg-3">
                <label class="control-label col-md-5" for="perf">PerfEnPegue</label>
                <div class="col-md-7">
            SI<input type="radio" class="form-control" id="PerfEnPegueS" name="PerfEnPegue" value='SI' required>
             NO<input type="radio" class="form-control" id="PerfEnPegueN" name="PerfEnPegue" value='NO' required> 
              
                    
                </div>
            </div>
            <div class="form-group col-sm-4 col-lg-3">
                <label class="control-label col-md-5" for="descPegue">DescPerfEnPegue</label>
                <div class="col-md-7">
                    <input type="text" class="form-control" id="DescPerfEnPegue" name="DescPerfEnPegue">
                </div>
            </div>
            <div class="form-group col-sm-4 col-lg-3">
                <label class="control-label col-md-5" for="rama">Rama</label>
                <div class="col-md-7">
                 SI<input type="radio" class="form-control" id="ramaS" name="rama" value='SI' required>
             NO<input type="radio" class="form-control" id="ramaN" name="rama" value='NO' required> 
              
                </div>
            </div>
            <div class="form-group col-sm-4 col-lg-3">
                <label class="control-label col-md-5" for="medRama">MedidaRama</label>
                <div class="col-md-7">
                    <input type="text" class="form-control" id="MedidaRama" name="MedidaRama">
                </div>
            </div>
            <div class="form-group col-sm-4 col-lg-3">
                <label class="control-label col-md-5" for="pinza">Pinza</label>
                <div class="col-md-7">
                SI<input type="radio" class="form-control" id="pinzaS" name="pinza" value='SI' required>
             NO<input type="radio" class="form-control" id="pinzaN" name="pinza" value='NO' required> 
              
                </div>
            </div>
            <div class="form-group col-sm-4 col-lg-3">
                <label class="control-label col-md-5" for="medPinza">MedidaPinza</label>
                <div class="col-md-7">
                    <input type="text" class="form-control" id="MedidaPinza" name="MedidaPinza">
                </div>
            </div>
            <div class="form-group col-sm-4 col-lg-3">
                <label class="control-label col-md-5" for="perfo">Perforaciones</label>
                <div class="col-md-7">
             SI<input type="radio" class="form-control" id="perforacionesS" name="perforaciones" value='SI' required>
             NO<input type="radio" class="form-control" id="perforacionesN" name="perforaciones" value='NO' required> 
               
                </div>
            </div>
            <div class="form-group col-sm-4 col-lg-3">
                <label class="control-label col-md-5" for="centerline">Centerline</label>
                <div class="col-md-7">
                SI<input type="radio" class="form-control" id="centerlineS" name="centerline" value='SI' required>
                 NO<input type="radio" class="form-control" id="centerlineN" name="centerline" value='NO' required>   
                </div>
            </div>
            <div class="form-group col-sm-4 col-lg-3">
                <label class="control-label col-md-5" for="medcenterline">MedidaCenterline</label>
                <div class="col-md-7">
                    <input type="text" class="form-control" id="MedidaCenterline" name="MedidaCenterline">
                </div>
            </div>
            <div class="form-group col-sm-4 col-lg-3">
                <label class="control-label col-md-5" for="desb">Desbarbe</label>
                <div class="col-md-7">
                 SI<input type="radio" class="form-control" id="desbardeS" name="desbarde" value='SI' required>
                 NO<input type="radio" class="form-control" id="desbardeN" name="desbarde" value='NO' required> 
                  
                </div>
            </div>
            <div class="form-group col-sm-4 col-lg-3">
                <label class="control-label col-md-5" for="Compensacion">Compensacion</label>
                <div class="col-md-7">
                SI<input type="radio" class="form-control" id="compensacionS" name="compensacion" value='SI' required>
                 NO<input type="radio" class="form-control" id="compensacionN" name="compensacion" value='NO' required> 
                  
                    
                </div>
            </div>
            <div class="form-group col-sm-4 col-lg-3">
                <label class="control-label col-md-5" for="NumPiezasCompensacion">NumPiezas</label>
                <div class="col-md-7">
                    <input type="text" class="form-control" id="NumPiezasCompensacion" name="NumPiezasCompensacion">
                </div>
            </div>
            <button type="submit" class="btn btn-primary" id="guardaMaquina">Guardar Maquina</button>
        </form>
        <!--form class="form-inline" role="form" method='POST' name='guardaMaquinas' id='guardaMaquinas'>
            <div class="form-group">
                <!--label for="cliente">Cliente</label>
                <input type='text' class="form-control" id="clienteM" name='clienteM'-->
            <!--/div>
            <div class="form-group">
                <label for="maq">Máquina</label>
                <select class="form-control" id="maq" name='maq'>
                         <option>Seleccionar...</option>
                  <?php 
                    //foreach ($this->tiposMaq as $key =>$option) {
                      //echo " <option>".$key."</option>";
                   // }



                  ?>
                </select>
            </div>
            <button type="submit" class="btn btn-default">Guardar</button>
        </form-->

    </div>
</div>


</div>
<br/>
<br/>

<ul class="nav nav-tabs class-clear">
    <li class="active" ><a data-toggle="tab" href="#home" id='menuContacto'>Contactos</a></li>
    <li ><a data-toggle="tab" href="#menu1" id='menuDir'>Direcciones</a></li>
    <li ><a data-toggle="tab" href="#menu2" id='clickM'>Máquinas</a></li>
</ul>

<div class="tab-content">
    <div id="home" class="tab-pane fade in active">
        <div class="col-md-12"><br>
           <button type="button" class="btn btn-success" id="btnNuevoContacto">+</button>
        <table id="gridContactos"></table>
            <div id="pgridContactos"></div>
        </div>
    </div>
    <div id="menu1" class="tab-pane fade">
        <div class="col-md-12"><br>
             <button type="button" class="btn btn-success" id="btnNuevoDireccion">+</button>

            <table id="gridDirecciones"></table>
            <div id="pgridDirecciones"></div>
        </div>
    </div>
    <div id="menu2" class="tab-pane fade">
         <div class="col-md-12"><br>
         <button type="button" class="btn btn-success" id="btnNuevoMaquina">+</button>
            <table id="gridMaquinas"></table>
            <div id="pgridMaquinas"></div>
        </div>
    </div>
</div>