
<button type="button" class="btn btn-success" id="btnNuevoUsuario">+</button>
<table id="gridUsuarios"></table>
 <div id="pgridUsuarios"></div>

<div id="dialog-usuarios" title="Nuevo usuario">
    <br/>
    <br/>
    <button type="button" id="btnEditarUsuario" class='btn btn-sm btn-primary'><span class="glyphicon glyphicon-pencil"></span>Editar</button>
    <!--ul class="checkbox-group" id="btnEditarUsuario">
        <li value="off"><span class="glyphicon glyphicon-pencil"></span>Editar</li>
    </ul-->
    <form class="form-horizontal" role="form" name="registraUsuarios" id="registraUsuarios" method="POST">
        <input type="hidden" id='identificadorUsuarios'/>
        <input type="hidden" name="idUsuario" id="idUsuario"/>
        <table class="table table-striped">
            <tbody>
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td class="td_right">Estatus:</td>
                    <td>
                        <select class="form-control" id="estatusUser" name="estatusUser" required>
                            <option>Seleccionar</option>
                            <option value="10">ACTIVO</option>
                            <option value="20">INACTIVO</option>   
                        </select>
                    </td>
                    <td></td>
                </tr>
                <tr>
                    <td class="td_right">Usuario:</td>
                    <td>
                        <input type="text" class="form-control" id="usuario" name='usuario' placeholder="Introduce usuario" required>
                    </td>
                    <td class="td_right">Password:</td>
                    <td>
                        <input type="password" class="form-control" id="pwd" name='pwd' placeholder="Introduce password" required>
                    </td>
                    <td class="td_right">Descripción:</td>
                    <td>
                        <input type="text" class="form-control" id="desc" name="desc" placeholder="Descripción" required>
                    </td>
                    <td class="td_right">Tipo:</td>
                    <td>
                        <select class="form-control" id="tipoUser" name="tipoUser" required>
                            <option>Seleccionar</option>
                            <?php 
                                print_r($this->datos); 
                                foreach ($this->datos as $option)
                                {
                                    echo " <option value='".$option['Id_tipousuario']."'>".$option['Descripcion']."</option>" ;
                                }
                            ?>
                        </select>
                    </td>
                    <td></td>
                </tr>
            </tbody>
        </table>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-sm btn-primary" id="regUsuarios">Registrar</button>
            </div>
        </div>
    </form>
</div>