<div class="container">
  <h2>Usuarios</h2>
  <form class="form-horizontal" role="form" name="registraUsuarios" id="registraUsuarios" method="POST">
    <div class="form-group">
      <label class="control-label col-sm-2" for="email">Usuario:</label>
      <div class="col-sm-2">
        <input type="text" class="form-control" id="usuario" name='usuario' placeholder="Introduce usuario">
      </div>
    </div>
    <div class="form-group">
      <label class="control-label col-sm-2" for="pwd">Password:</label>
      <div class="col-sm-2">
        <input type="password" class="form-control" id="pwd" name='pwd' placeholder="Introduce password">
      </div>
    </div>
  <div class="form-group">
      <label class="control-label col-sm-2" for="desc">Descripción:</label>
      <div class="col-sm-2">
        <input type="text" class="form-control" id="desc" name="desc" placeholder="Descripción">
      </div>
    </div>
    <div class="form-group">
      <label class="control-label col-sm-2" for="tipo">Tipo:</label>
      <div class="col-sm-2">
     <select class="form-control" id="tipoUser" name="tipoUser">
        <option>Seleccionar</option>
       <?php print_r($this->datos); 
        		foreach ($this->datos as $option) {
        		echo " <option value='".$option['Id_tipousuario']."'>".$option['Descripcion']."</option>" ;
        		}

        ?>

      </select>
     </div>
     </div>
       <div class="form-group">
      <label class="control-label col-sm-2" for="tipo">Estatus:</label>
      <div class="col-sm-2">
     <select class="form-control" id="estatusUser" name="estatusUser">
        <option>Seleccionar</option>
        <option value="10">ACTIVO</option>
        <option value="20">INACTIVO</option>
       
      </select>
     </div>
     </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-primary">Registrar</button>
      </div>
    </div>
  </form>
</div>