




<button type="button" id="maq1" class='btn btn-primary'>Máquina1</button>
<button type="button" id="maq2" class='btn btn-primary'>Máquina2</button>
<button type="button" id="maq3" class='btn btn-primary'>Máquina3</button>
<button type="button" id="maq4" class='btn btn-primary'>Máquina4</button>
<button type="button" id="maq5" class='btn btn-primary'>Máquina5</button>
<button type="button" id="maq6" class='btn btn-primary'>Máquina6</button>
<table id="disenoProceso"></table>
<div id="disenoProcesop"></div>
<button type="button" id="procesar" class='btn btn-primary'>Procesar</button>
 <table id="diseno"></table>
<div id="disenop"></div>
<div id="dialog-produccion-pendiente" title="Detalle Orden :: proceso Diseño"></div>

