
        <div id="hasLogin">
            <center>
                <div id="log">
                    <br/>
                 <img  id='logoLogin' src="images/header_logo.png" />
                    <br><form name="login" id="login" method="POST">
                    <table>
                        <tr>
                            <td class="tdlabel">
                                <label for="Usuario">Usuario: <span>&#42;</span></label></td>
                            <td>
                                <input type="text" name="usuario" id="usuario"  >
                            </td>
                        </tr>
                        <tr>
                            <td class="tdlabel">
                                <label for="password">Contrase&ntilde;a: <span>&#42;</span></label>
                            </td>
                            <td>
                              <input type="password" name="password" id="password" >
                            </td>
                        </tr>
                    </table>
                        <br><div id="error"></div>
                    <div class="btnentrar">
                        <input type="submit" class="btn btn-primary" name="login" id="login" value="Entrar   &#9658;">
                    </div></form>
                    <br/>
                    <br/>
                </div>
            </center>
        </div>
        <div id="cargandoo"></div>
    </center>
</body>