<div class="col-xs-10 col-md-6 col-xs-offset-1 col-md-offset-3">
    <div id="divlogin">
        <img  id="logoLogin" class="img-responsive" src="images/header_logo.png" />
        <form name="login" id="login" method="POST" class="form-horizontal">
            <br/>
            <div class="form-group">
                <label for="Usuario" class="control-label col-sm-3">Usuario: <span>&#42;</span></label>
                <div class="col-sm-9">
                    <input type="text" name="usuario" id="usuario" class="form-control"/>
                </div>
            </div>
            <div class="form-group">
                <label for="password" class="control-label col-sm-3">Contrase&ntilde;a: <span>&#42;</span></label>
                <div class="col-sm-9">
                    <input type="password" name="password" id="password" class="form-control"/>
                </div>
            </div>
            <br/>
            <div class="btnentrar">
                <input type="submit" class="btn btn-primary" name="login" id="login" value="Entrar   &#9658;">
            </div>
        </form>
    </div>
</div>