<?php
    $front =Zend_Controller_Front :: getInstance (); 
    $baseUrl = $front -> getBaseUrl ();
    echo "<META HTTP-EQUIV='Refresh' CONTENT='0; URL=$baseUrl/Login'>";
?>
<html lang="es">
    <head>
        <title>Saliendo del sistma</title>
        <link rel="stylesheet" 	type="text/css" media="screen" 	href="<?php echo $this->baseUrl(); ?>/css/bootstrap/bootstrap.min.css" />
        <script type="text/javascript" charset="utf-8" src="<?php echo $this->baseUrl(); ?>/js/bootstrap/bootstrap.min.js"></script>
        <style>
            @font-face
            {
                font-family:'FontAwesome';
                src:url('<?php echo $this->baseUrl(); ?>/font/fontawesome-webfont.eot?v=4.0.1');
                src:url('<?php echo $this->baseUrl(); ?>/font/fontawesome-webfont.eot?#iefix&v=4.0.1') 
                    format('embedded-opentype'),url('<?php echo $this->baseUrl(); ?>/font/fontawesome-webfont.woff?v=4.0.1') 
                    format('woff'),url('<?php echo $this->baseUrl(); ?>/font/fontawesome-webfont.ttf?v=4.0.1') 
                    format('truetype'),url('<?php echo $this->baseUrl(); ?>/font/fontawesome-webfont.svg?v=4.0.1#fontawesomeregular') 
                    format('svg');
                font-weight:normal;
                font-style:normal
            }
            
            body
            {
                background: rgba(206,239,254,1);
                background: -moz-linear-gradient(top, rgba(206,239,254,1) 0%, rgba(255,255,255,1) 100%);
                background: -webkit-gradient(left top, left bottom, color-stop(0%, rgba(206,239,254,1)), color-stop(100%, rgba(255,255,255,1)));
                background: -webkit-linear-gradient(top, rgba(206,239,254,1) 0%, rgba(255,255,255,1) 100%);
                background: -o-linear-gradient(top, rgba(206,239,254,1) 0%, rgba(255,255,255,1) 100%);
                background: -ms-linear-gradient(top, rgba(206,239,254,1) 0%, rgba(255,255,255,1) 100%);
                background: linear-gradient(to bottom, rgba(206,239,254,1) 0%, rgba(255,255,255,1) 100%);
                filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#ceeffe', endColorstr='#ffffff', GradientType=0 );
                background-repeat: no-repeat;
            }
            
            #contenidobody
            {
                margin-top: 100px;
                padding-top: 20px;
                margin-bottom: 0;
                height: 100%;
            }
            
            h1
            {
                text-align: center;
                font-family:'FontAwesome';
                color: #fff;
                text-shadow: 0px 0px 2px #000;
            }
        </style>
    </head>
    <body>
        <section>
            <div id="contenidobody">
                <div class="container">
                    <div class="row">
                        <div class="col-xs-10 col-md-6 col-xs-offset-1 col-md-offset-3">
                            <h1>SALIENDO DEL SISTEMA...</h1>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </body>
</html>