<?php echo $this->doctype() ?>
    <head>
        <?php 
            $this->headMeta()->prependHttpEquiv('Content-Type', 'text/html; charset=utf-8');
            $this->headLink()->appendStylesheet($this->baseUrl('css/bootstrap/bootstrap.min.css'));
            $this->headLink()->appendStylesheet($this->baseUrl('css/jquery-ui.css'));
            $this->headLink()->appendStylesheet($this->baseUrl('css/estilo.css'));
            $this->headLink()->appendStylesheet($this->baseUrl('css/estilos_txt.css'));
            $this->headLink()->appendStylesheet($this->baseUrl('css/theme.blue.css'));
            $this->headLink()->appendStylesheet($this->baseUrl('css/ui.jqgrid.css'));
            $this->headLink()->appendStylesheet($this->baseUrl('css/jquery-ui-1.10.4.custom.min.css'));
            $this->headScript()->prependFile($this->baseUrl('js/jquery-1.12.3.min.js'), 'text/javascript');
            $this->headScript()->appendFile($this->baseUrl('js/jquery-ui-custom.min.js'), 'text/javascript');
            $this->headScript()->appendFile($this->baseUrl('js/bootstrap/bootstrap.min.js'), 'text/javascript');
            $this->headScript()->appendFile($this->baseUrl('js/script.js'), 'text/javascript');
            $this->headScript()->appendFile($this->baseUrl('js/guardarClientes.js'), 'text/javascript');
            $this->headScript()->appendFile($this->baseUrl('js/grid.js'), 'text/javascript');
            $this->headScript()->appendFile($this->baseUrl('js/gridContactos.js'), 'text/javascript');
             $this->headScript()->appendFile($this->baseUrl('js/gridDirecciones.js'), 'text/javascript');
            $this->headScript()->appendFile($this->baseUrl('js/grid.locale-en.js'), 'text/javascript');
            $this->headScript()->appendFile($this->baseUrl('js/jquery.jqGrid.min.js'), 'text/javascript');
            $this->headTitle()->append('Miapp/Suajes');
            echo $this->headMeta();
            echo $this->headTitle(); 
            echo $this->headLink();
            echo $this->headScript();
        ?>
        <script>
            var path = "<?php echo $this->baseUrl(); ?>";//por si queremos la url base en js
        </script>
        <script type="text/javascript">
            $(document).ready(function()
            {
                errores=sessionStorage.getItem("id");
                if(errores!="")
                {
                    $("#notificaciones").html("Consulta exitosa");
                }
                else
                {
                    $("#notificaciones").html("A ocurrido error");
                }
            })
        </script>
        <script language="JavaScript"> 
            function mueveReloj()
            { 
                momentoActual = new Date();
                hora = momentoActual.getHours();
                minuto = momentoActual.getMinutes();
                segundo = momentoActual.getSeconds();
                if(segundo<10)
                {
                    segundo="0"+segundo;
                }
                if(minuto<10)
                {
                    minuto="0"+minuto;
                }
                horaImprimible = hora + " : " + minuto + " : " + segundo;
                $("#hora").html(horaImprimible);
            } 
           setInterval (function() {mueveReloj();}, 500); 
        </script> 
    </head>
    <body onload="mueveReloj()" >		
        <header>
            <div id="div-img-head">
                <div class="container">
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="sombra-nav">
                                <nav class="navbar navbar-inverse navbar_top navbar-inverse_top">
                                    <div class="container-fluid">
                                        <div class="navbar-header">
                                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#Navbar_top">
                                                <span class="icon-bar"></span>
                                                <span class="icon-bar"></span>
                                                <span class="icon-bar"></span> 
                                            </button>
                                            <a class="navbar-brand navbar-brand_top hidden-xs hidden-sm" href="#"><img id="logo_viveros" src="images/header/logo_viveros.png"/></a>
                                        </div>
                                        <div class="collapse navbar-collapse" id="Navbar_top">
                                            <ul class="nav navbar-nav navbar-right nav_top navbar-nav_top">
                                                <!--formar el menu -->
                                        <!--li class='active'><a href='index' >Inicio</a>   </li-->  
                                       <?php 
                                            $crearmenu = new Zend_Session_Namespace('crearmenu'); 
                                            $m=$crearmenu->menu;
                                            $armarMenu = new Application_Model_Menu_Constructor();
                                             //echo $armarMenu->getinicio();

                                            foreach ($m as $key => $valor){
                                         if($valor['mnuCatalogos']==1){
                                            echo   $armarMenu->getcatalogos($valor['mnuCatalogoclientes']);

                                             }
                                           if($valor['mnuPlaneacion']==1){
                                            echo $armarMenu->getplaneacion();

                                            }
                                             if($valor['mnuProduccion']==1){
            echo $armarMenu->getproduccion($valor['mnuDiseno'],$valor['mnuCorte'],$valor['mnuDoblado'],$valor['mnuArmado'],$valor['mnuAhulado'],$valor['mnuRouter']);

                                            }
                                             if($valor['mnuEntregas']==1){
                                            echo $armarMenu->getentregas();

                                            }
                                             if($valor['mnuUsuarios']==1){
                                           // echo $armarMenu->getusuarios();

                                            }
                                              if($valor['mnuMonitor']==1){
                                            echo $armarMenu->getmonitor();

                                            }
                                            
                                            //echo $armarMenu->getsalir();

                                            }?>
                                            <li>
                                             <a href='login/salir'>Salir</a></li>

                                                <!--fin de menu-->
                                            </ul>
                                        </div>
                                    </div>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <section>
            <div id="contenidobody">
                <div class="container">
                    <div class="row">
                        <div class="col-xs-12">
                            <nav class="navbar navbar-inverse">
                                <div class="container-fluid">
                                    <div class="navbar-header">
                                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                                            <span class="icon-bar"></span>
                                            <span class="icon-bar"></span>
                                            <span class="icon-bar"></span> 
                                        </button>
                                        <!--<a class="navbar-brand" href="#">Barra de acciones</a>-->
                                    </div>
                                    <div class="collapse navbar-collapse" id="myNavbar">

                                        <ul class="nav navbar-nav">
                                            
                                            <li class="dropdown">
                                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">Nuevo <span class="caret"></span></a>
                                                <ul class="dropdown-menu">
                                                    <?php  
                                                 
                                                   if($_SERVER['REQUEST_URI']=="/viverosV2/public/consultas"){
                                                    echo " <li><a href='#'' id='nuevoCliente' >Cliente</a></li>";
                                                   }else{ ?>

                                                   
                                                    <li><a href="#" id="nuevoCliente">Cliente</a></li>
                                                    <li><a href="#" id="nuevoContacto">Contacto</a></li>
                                                    <li><a href="#" id="nuevaDireccion">Dirección</a></li>
                                                    <li><a href="#" id="nuevaMaquina">Máquina</a></li>

                                                   <?php  }?>


                                               </ul>
                                            </li>
                                             <li><a href="#" id="guardaCliente">Guardar</a></li>
                                             <li><a href="#" id="cancelaClienteUno">Cancelar</a></li>
                                        </ul>

                                    </div>
                                </div>
                            </nav>
                       </div>
                    </div>
                </div>
                <div class="container">
                    <div class="row">
                        <div class="col-xs-12">
                            <?= $this->layout()->content; ?>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-xs-12">
                        <div id="notificaciones" class="col-xs-8 col-sm-3">Error de consutla</div>
                <?php
                $this->datosUsuario = Zend_Auth::getInstance()->getStorage()->read();
                    $usuario=$personadid= $this->datosUsuario->Usuario;
                ?>
                        <div id="usr" class="col-xs-4 col-sm-3"><?php echo $usuario; ?></div>
                        <div id="fecha" class="col-sm-2 hidden-xs"><?php echo date("d-m-Y"); ?></div>
                        <div id="hora" class="col-sm-2 hidden-xs"></div>
                        <div class="col-sm-2 hidden-xs">Version. 160602</div>
                    </div>
                </div>
            </div>
        </footer>
    </body>
</html>