<?php echo $this->doctype() ?>
<head>
    <?php 
        $this->headMeta()->prependHttpEquiv('Content-Type', 'text/html; charset=utf-8');
        $this->headLink()->appendStylesheet($this->baseUrl('css/bootstrap/bootstrap.min.css'));
        $this->headLink()->appendStylesheet($this->baseUrl('css/jquery-ui.css'));
        $this->headLink()->appendStylesheet($this->baseUrl('css/estilo.css'));
        $this->headLink()->appendStylesheet($this->baseUrl('css/estilos_txt.css'));
        $this->headLink()->appendStylesheet($this->baseUrl('css/theme.blue.css'));
        $this->headLink()->appendStylesheet($this->baseUrl('css/ui.jqgrid.css'));
        $this->headLink()->appendStylesheet($this->baseUrl('css/jquery-ui-1.10.4.custom.min.css'));
        $this->headScript()->prependFile($this->baseUrl('js/jquery-1.12.3.min.js'), 'text/javascript');
        $this->headScript()->appendFile($this->baseUrl('js/jquery-ui-custom.min.js'), 'text/javascript');
        $this->headScript()->appendFile($this->baseUrl('js/bootstrap/bootstrap.min.js'), 'text/javascript');
        $this->headScript()->appendFile($this->baseUrl('js/script.js'), 'text/javascript');
        $this->headScript()->appendFile($this->baseUrl('js/guardarClientes.js'), 'text/javascript');
        $this->headScript()->appendFile($this->baseUrl('js/grid.js'), 'text/javascript');
        $this->headScript()->appendFile($this->baseUrl('js/gridContactos.js'), 'text/javascript');
         $this->headScript()->appendFile($this->baseUrl('js/gridDirecciones.js'), 'text/javascript');
        $this->headScript()->appendFile($this->baseUrl('js/grid.locale-en.js'), 'text/javascript');
        $this->headScript()->appendFile($this->baseUrl('js/jquery.jqGrid.min.js'), 'text/javascript');
        $this->headTitle()->append('Miapp/Suajes');

        echo $this->headMeta();
        echo $this->headTitle(); 
        echo $this->headLink();
        echo $this->headScript();
    ?>
    <script>
        var path = "<?php echo $this->baseUrl(); ?>";//por si queremos la url base en js
    </script>
    </head>
    <body>		
        <header>
            <div id="div-img-head">
                <div class="container">
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="sombra-nav">
                                <nav class="navbar navbar-inverse navbar_top navbar-inverse_top">
                                    <div class="container-fluid">
                                        <div class="navbar-header">
                                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#Navbar_top">
                                                <span class="icon-bar"></span>
                                                <span class="icon-bar"></span>
                                                <span class="icon-bar"></span> 
                                            </button>
                                            <a class="navbar-brand navbar-brand_top hidden-xs hidden-sm" href="#"><img id="logo_viveros" src="images/header/logo_viveros.png"/></a>
                                        </div>
                                        <div class="collapse navbar-collapse" id="Navbar_top">
                                            <ul class="nav navbar-nav navbar-right nav_top navbar-nav_top">
                                                <li class="active"><a href="index">Inicio</a></li>
                                                  <li class="dropdown">
                                                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Catalogos <span class="caret"></span></a>
                                                    <ul class="dropdown-menu">
                                                        Clientes
                                                      
                                                        <li><a href="consultas">Consultas</a></li>
                                                        <li><a href="altas">Altas</a></li>
                                                        Maquinas
                                                       
                                                        <li><a href="consultas">Consultas</a></li>
                                                        <li><a href="altas">Altas</a></li>
                                                   </ul>
                                                </li>
                                                <li class="dropdown">
                                                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Clientes <span class="caret"></span></a>
                                                    <ul class="dropdown-menu">
                                                        <li><a href="consultas">Consultas</a></li>
                                                        <li><a href="altas">Altas</a></li>
                                                   </ul>
                                                </li>
                                                <li><a href="#">Producción</a></li>
                                                <li><a href="#">Reportes</a></li>
                                                <li><a href="#">Login</a></li>
                                                <!--<li><a href="#">Logout</a></li>-->
                                            </ul>
                                        </div>
                                    </div>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <section>
            <div id="contenidobody">
                <div class="container">
                    <div class="row">
                        <div class="col-xs-12">
                            <nav class="navbar navbar-inverse">
                                <div class="container-fluid">
                                    <div class="navbar-header">
                                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                                            <span class="icon-bar"></span>
                                            <span class="icon-bar"></span>
                                            <span class="icon-bar"></span> 
                                        </button>
                                        <a class="navbar-brand" href="#">Barra de acciones</a>
                                    </div>
                                    <div class="collapse navbar-collapse" id="myNavbar">
                                        <ul class="nav navbar-nav">
                                            <li class="active"><a href="#">Home</a></li>
                                            <li><a href="#">Page 1</a></li>
                                            <li><a href="#">Page 2</a></li> 
                                            <li><a href="#">Page 3</a></li> 
                                        </ul>
                                        <ul class="nav navbar-nav navbar-right">
                                            <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
                                            <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </nav>
                        </div>
                    </div>
                </div>
                <div class="container">
                    <div class="row">
                        <?= $this->layout()->content; ?>
                    </div>
                </div>
            </div>
        </section>
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-xs-12">
                        <div id="notificaciones" class="col-xs-8 col-sm-3">Error de consutla</div>
                        <div id="usr" class="col-xs-4 col-sm-3">Usuario</div>
                        <div id="fecha" class="col-sm-2 hidden-xs">Fecha</div>
                        <div id="hora" class="col-sm-2 hidden-xs">Hora</div>
                        <div class="col-sm-2 hidden-xs">Version. 160602</div>
                    </div>
                </div>
            </div>
        </footer>
    </body>
</html>