<form id="op" class="form-inline" name="op" method="POST">
    <!--Indicaciones generales-->
    <table class="table table-striped">
        <button id="btn_collapse_ig_in" class="btn btn-sm btn-info" type="button" data-toggle="collapse" data-target="#indicaciones_generales"><img class="btn_collapse_img" src="<?php echo $this->baseUrl(); ?>/images/collapse_in.png"/></button>
        <button id="btn_collapse_ig" class="btn btn-sm btn-info display_none" type="button" data-toggle="collapse" data-target="#indicaciones_generales"><img class="btn_collapse_img" src="<?php echo $this->baseUrl(); ?>/images/collapse.png"/></button>
        <thead>
            <tr>
                <th colspan="10">INDICACIONES GENERALES</th>
            </tr>
        </thead>
        <tbody id="indicaciones_generales" class="collapse in">
            <tr>
                <td class="td_right">Cliente:</td>
                <td colspan="4">
                    <select id="op_ig_cliente" class="form-control" name="op_ig_cliente">
                        <option>Seleccionar ...</option>
                    </select>
                </td>
                <td class="td_right">Fecha Orden:</td>
                <td><input id="op_ig_fecha_orden" class="form-control op_input" type="date" name="op_ig_fecha_orden"/></td>
                <td class="td_right">id Orden:</td>
                <td><input id="op_ig_id_orden" class="form-control op_input" type="text" name="op_ig_id_orden"/></td>
                <td></td>
            </tr>
            <tr>
                <td class="td_right">Nombre Trabajo</td>
                <td colspan="4"><input id="op_ig_nombre_trabajo" class="form-control op_input" type="text" name="op_ig_nombre_trabajo"/></td>
                <td class="td_right">Fecha entrega</td>
                <td><input id="op_ig_fecha_entrega" class="form-control op_input" type="date" name="op_ig_fecha_entrega"/></td>
                <td class="td_right">Prioridad</td>
                <td>
                    <select id="op_ig_prioridad" class="form-control" name="op_ig_prioridad">
                        <option>Seleccionar ...</option>
                    </select>
                </td>
                <td></td>
            </tr>
            <tr>
                <td class="td_right">Tipo Trabajo:</td>
                <td colspan="4">
                    <select id="op_ig_tipo_trabajo" class="form-control" name="op_ig_tipo_trabajo">
                        <option>Seleccionar ...</option>
                    </select>
                </td>
                <td class="td_right">Desarrollo con:</td>
                <td colspan="3">
                    <select id="op_ig_desarrollo_con" class="form-control" name="op_ig_desarrollo_con">
                        <option>Seleccionar ...</option>
                    </select>
                </td>
                <td></td>
            </tr>
            <tr>
                <td class="td_right">Material:</td>
                <td colspan="4">
                    <select id="op_ig_material" class="form-control" name="op_ig_material">
                        <option>Seleccionar ...</option>
                    </select>
                </td>
                <td class="td_right">Sustrato:</td>
                <td colspan="3">
                    <select id="op_ig_sustrato" class="form-control" name="op_ig_sustrato">
                        <option>Seleccionar ...</option>
                    </select>
                </td>
                <td></td>
            </tr>
            <tr>
                <td class="td_right">Complejidad:</td>
                <td colspan="4">
                    <select id="op_ig_complejidad" class="form-control" name="op_ig_complejidad">
                        <option>Seleccionar ...</option>
                    </select>
                </td>
                <td class="td_right" colspan="5">
                    <button type="button" class="btn btn-sm btn-success" id="btnRegresarOrdenes">Regresar</button>
                    <button type="button" class="btn btn-sm btn-success" id="btnLiberarOrdenes">Liberar</button>
                </td>
            </tr>
        </tbody>
    </table>
    <!--Indicaciones generales-->
    <!--Indicaciones para elaborar suajes-->
    <table class="table table-striped">
        <button id="btn_collapse_ipes_in" class="btn btn-sm btn-info" type="button" data-toggle="collapse" data-target="#indicaciones_para_elaborar_suajes"><img class="btn_collapse_img" src="<?php echo $this->baseUrl(); ?>/images/collapse_in.png"/></button>
        <button id="btn_collapse_ipes" class="btn btn-sm btn-info display_none" type="button" data-toggle="collapse" data-target="#indicaciones_para_elaborar_suajes"><img class="btn_collapse_img" src="<?php echo $this->baseUrl(); ?>/images/collapse.png"/></button>
        <thead>
            <tr>
                <th colspan="10">INDICACIONES PARA ELABORAR SUAJE</th>
            </tr>
        </thead>
        <tbody id="indicaciones_para_elaborar_suajes" class="collapse in">
            <tr>
                <td class="td_right">Máquina:</td>
                <td colspan="4">
                    <select id="op_suajes_maquina" class="form-control" name="op_suajes_maquina">
                        <option>Seleccionar ...</option>
                    </select>
                </td>
                <td></td>
                <td></td>
                <td class="td_right">id Maquina Cliente:</td>
                <td><input id="op_suajes_id_maquina_cliente" class="form-control op_input" type="text" name="op_suajes_id_maquina_cliente"/></td>
                <td></td>
            </tr>
            <tr>
                <td class="td_right">Madera:</td>
                <td colspan="3">
                    <select id="op_suajes_madera" class="form-control">
                        <option>Seleccionar ...</option>
                    </select>
                </td>
                <td class="td_right">Rama:</td>
                <td>
                    <div class="radio">
                        <label><input id="op_suajes_rama_si" type="radio" name="op_suajes_rama" value="si">Si</label>
                        <label><input id="op_suajes_rama_no" type="radio" name="op_suajes_rama" value="no">No</label>
                    </div>
                </td>
                <td><input id="op_suajes_rama_1" class="form-control op_input" type="text"/></td>
                <td class="td_right">Pinza:</td>
                <td>
                    <div class="radio">
                        <label><input id="op_suajes_pinza_si" type="radio" name="op_suajes_pinza" value="si" >Si</label>
                        <label><input id="op_suajes_pinza_no" type="radio" name="op_suajes_pinza" value="no">No</label>
                    </div>
                </td>
                <td></td>
            </tr>
            <tr>
                <td class="td_right">Perforaciones:</td>
                <td>
                    <div class="radio">
                        <label><input id="op_suajes_perforaciones_si" type="radio" name="op_suajes_perforaciones" value="si">Si</label>
                        <label><input id="op_suajes_perforaciones_n" type="radio" name="op_suajes_perforaciones" value="no">No</label>
                    </div>
                </td>
                <td class="td_right">Desbarbe:</td>
                <td>
                    <div class="radio">
                        <label><input id="op_suajes_desbarbe_si" class="form-control" type="radio" name="op_suajes_desbarbe" value="si"> Si</label>
                        <label><input id="op_suajes_desbarbe_no" class="form-control" type="radio" name="op_suajes_desbarbe" value="no"> No</label>
                    </div>
                </td>
                <td class="td_right">Compensación:</td>
                <td>
                    <div class="radio">
                        <label><input id="op_suajes_compensación_si" type="radio" name="op_suajes_compensación" value="si">Si</label>
                        <label><input id="op_suajes_compensación_no" type="radio" name="op_suajes_compensación" value="no">No</label>
                    </div>
                </td>
                <td class="td_right">Centerline</td>
                <td>
                    <div class="radio">
                        <label><input id="op_suajes_centerline_si" type="radio" name="op_suajes_centerline" value="si">Si</label>
                        <label><input id="op_suajes_centerline_no" type="radio" name="op_suajes_centerline" value="no">No</label>
                    </div>
                </td>
                <td><input id="op_suajes_centerline_input" class="form-control op_input" type="text" name="op_suajes_centerline_input"/></td>
                <td></td>
            </tr>
            <tr>
                <td colspan="10"></td>
            </tr>
            <tr>
                <td class="td_right">Frente de suaje:</td>
                <td>
                    <label><input id="op_suajes_frente_suaje_si" type="radio" name="op_suajes_frente_suaje" value="si">Si</label>
                    <label><input id="op_suajes_frente_suaje_no" type="radio" name="op_suajes_frente_suaje" value="no">No</label>
                </td>
                <td></td>
                <td></td>
                <td class="td_right">Corte:</td>
                <td>
                    <select id="op_suajes_corte" class="form-control" name="op_suajes_corte">
                        <option>Seleccionar ...</option>
                    </select>
                </td>
                <td></td>
                <td class="td_right">Doblez:</td>
                <td>
                    <select id="op_suajes_dobles" class="form-control" name="op_suajes_dobles">
                        <option>Seleccionar ...</option>
                    </select>
                </td>
                <td></td>
            </tr>
            <tr>
                <td class="td_right">Perforado:</td>
                <td colspan="2">
                    <select id="op_suajes_perforado" class="form-control" name="op_suajes_perforado">
                        <option>Seleccionar ...</option>
                    </select>
                </td>
                <td></td>
                <td class="td_right">Precorte:</td>
                <td>
                    <select id="op_suajes_precorte" class="form-control" name="op_suajes_precorte">
                        <option>Seleccionar ...</option>
                    </select>
                </td>
                <td></td>
                <td class="td_right">Sacabocados</td>
                <td>
                    <select id="op_suajes_sacabocados" class="form-control" name="op_suajes_sacabocados">
                        <option>Seleccionar ...</option>
                    </select>
                </td>
                <td></td>
            </tr>
            <tr>
                <td class="td_right">Descuento:</td>
                <td colspan="2">
                    <select id="op_suajes_descuento" class="form-control" name="op_suajes_descuento">
                        <option>Seleccionar ...</option>
                    </select>
                </td>
                <td></td>
                <td class="td_right">Tipo de Corte:</td>
                <td>
                    <select id="op_suajes_tipo_de_corte" class="form-control" name="op_suajes_tipo_de_corte">
                        <option>Seleccionar ...</option>
                    </select>
                </td>
                <td></td>
                <td class="td_right">Placa:</td>
                <td>
                    <select id="op_suajes_placa" class="form-control" name="op_suajes_placa">
                        <option>Seleccionar ...</option>
                    </select>
                </td>
                <td></td>
            </tr>
            <tr>
                <td class="td_right">Nota:</td>
                <td colspan="8"><textarea id="op_suajes_nota" class="form-control textarea" name="op_suajes_nota" rows="2"></textarea></td>
                <td></td>
            </tr>
        </tbody>
    </table>
    <!--Indicaciones para elaborar suajes-->
    <!--Indicaciones elaboracion de trablas limpiadoras-->
    <table class="table table-striped">
        <thead>
            <tr>
                <th colspan="7">INDICACIONES ELABORACION DE TABLAS LIMPIADORAS</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td class="td_center" colspan="7">Tabla Hembra</td>
            </tr>
            <tr>
                <td class="td_right">Madera:</td>
                <td>
                    <select id="op_tablimp_madera_1" class="form-control">
                        <option>Seleccionar ...</option>
                    </select>
                </td>
                <td><input id="op_tablimp_madera_2" class="form-control op_input" type="text"/></td>
                <td class="td_right">Fte. Tabla:</td>
                <td>
                    <label><input id="op_tablimp_ftetab_si" class="form-control" type="radio" name="compensación" value="si" checked> Si</label>
                    <label><input id="op_tablimp_ftetab_no" class="form-control" type="radio" name="compensación" value="no"> No</label>
                </td>
                <td colspan="2"><input id="op_tablimp_ftetab" class="form-control op_input" type="text"/></td>
            </tr>
            <tr>
                <td class="td_right">Tipo:</td>
                <td>
                    <select id="op_tablimp_madera_1" class="form-control">
                        <option>Seleccionar ...</option>
                    </select>
                </td>
                <td><input id="op_tablimp_madera_2" class="form-control op_input" type="text"/></td>
                <td class="td_right">Rama</td>
                <td>
                    <label><input id="op_tablimp_rama_si" class="form-control" type="radio" name="compensación" value="si" checked> Si</label>
                    <label><input id="op_tablimp_rama_no" class="form-control" type="radio" name="compensación" value="no"> No</label>
                </td>
                <td colspan="2"><input id="op_tablimp_rama" class="form-control op_input" type="text"/></td>
            </tr>
            <tr>
                <td class="td_center" colspan="7">Tabla Macho</td>
            </tr>
            <tr>
                <td class="td_right">Fte de suaje:</td>
                <td>
                    <select id="op_tablimp_ftesuaje_1" class="form-control">
                        <option>Seleccionar ...</option>
                    </select>
                </td>
                <td><input id="op_tablimp_ftesuaje_2" class="form-control op_input" type="text"/></td>
                <td class="td_right">Pinza</td>
                <td>
                    <label><input id="op_tablimp_pinza_si" class="form-control" type="radio" name="compensación" value="si" checked> Si</label>
                    <label><input id="op_tablimp_pinza_no" class="form-control" type="radio" name="compensación" value="no"> No</label>
                </td>
                <td><input id="op_tablimp_pinza_1" class="form-control op_input" type="text"/></td>
                <td><input id="op_tablimp_pinza_2" class="form-control op_input" type="text"/></td>
            </tr>
            <tr>
                <td class="td_right">Corte:</td>
                <td>
                    <select id="op_tablimp_corte_1" class="form-control">
                        <option>Seleccionar ...</option>
                    </select>
                </td>
                <td><input id="op_tablimp_corte_2" class="form-control op_input" type="text"/></td>
                <td class="td_right">Perforaciones</td>
                <td>
                    <label><input id="op_tablimp_perforaciones_si" class="form-control" type="radio" name="compensación" value="si" checked> Si</label>
                    <label><input id="op_tablimp_perforaciones_no" class="form-control" type="radio" name="compensación" value="no"> No</label>
                </td>
                <td><input id="op_tablimp_perforaciones_1" class="form-control op_input" type="text"/></td>
                <td><input id="op_tablimp_perforaciones_2" class="form-control op_input" type="text"/></td>
            </tr>
        </tbody>
    </table>
    <div class="col-xs-12 observaciones">Observaciones: <textarea id="observaciones_2" class="form-control textarea" name="observaciones_2" rows="1"></textarea></div>
    <!--Indicaciones elaboracion de trablas limpiadoras-->
    <!--INDICACIONES ELABORACION DE  PERTINAX-->
    <table class="table table-striped">
        <thead>
            <tr>
                <th colspan="5">INDICACIONES ELABORACION DE  PERTINAX</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td class="td_right">Materia:</td>
                <td>
                    <select id="op_pertinax_materia" class="form-control">
                        <option>Seleccionar ...</option>
                    </select>
                </td>
                <td class="td_right">Calibre</td>
                <td colspan="2">
                    <select id="op_pertinax_calibre" class="form-control">
                        <option>Seleccionar ...</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td class="td_right">Ancho hilo:</td>
                <td>
                    <select id="op_pertinax_anchohilo_1" class="form-control">
                        <option>Seleccionar ...</option>
                    </select>
                </td>
                <td><input id="op_pertinax_anchohilo" class="form-control op_input" type="text"/></td>
                <td class="td_right">Piezas:</td>
                <td>
                    <select id="op_pertinax_piezas_1" class="form-control">
                        <option>Seleccionar ...</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td class="td_right">Ancho contrahilo:</td>
                <td>
                    <select id="op_pertinax_materia" class="form-control">
                        <option>Seleccionar ...</option>
                    </select>
                </td>
                <td colspan="3"><input id="op_pertinax_materia1" class="form-control op_input" type="text"/></td>
            </tr>
            <tr>
                <td class="td_right">Profundidad:</td>
                <td>
                    <select id="op_pertinax_materia" class="form-control">
                        <option>Seleccionar ...</option>
                    </select>
                </td>
                <td colspan="3"><input id="op_pertinax_materia1" class="form-control op_input" type="text"/></td>
            </tr>
        </tbody>
    </table>
    <div class="col-xs-12 observaciones">Observaciones: <textarea id="observaciones_3" class="form-control textarea" name="observaciones_3" rows="1"></textarea></div>
    <!--INDICACIONES ELABORACION DE  PERTINAX-->
    <!--INDICACIONES ELABORACION DE  LAMINAS RAYADAS-->
    <table class="table table-striped">
        <thead>
            <tr>
                <th colspan="5">INDICACIONES ELABORACION DE  LAMINAS RAYADAS</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td class="td_right">Lámina:</td>
                <td colspan="4">
                    <select id="op_lamrayadas_lam" class="form-control">
                        <option>Seleccionar ...</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td class="td_right">Ancho hilo:</td>
                <td>
                    <select id="op_lamrayadas_anchohilo_1" class="form-control">
                        <option>Seleccionar ...</option>
                    </select>
                </td>
                <td><input id="op_lamrayadas_anchohilo" class="form-control op_input" type="text"/></td>
                <td class="td_right">No. cajas:</td>
                <td>
                    <select id="op_lamrayadas_piezas_1" class="form-control">
                        <option>Seleccionar ...</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td class="td_right">Ancho contrahilo:</td>
                <td>
                    <select id="op_lamrayadas_materia" class="form-control">
                        <option>Seleccionar ...</option>
                    </select>
                </td>
                <td colspan="3"><input id="op_lamrayadas_materia1" class="form-control op_input" type="text"/></td>
            </tr>
            <tr>
                <td class="td_right">Profundidad:</td>
                <td>
                    <select id="op_lamrayadas_materia" class="form-control">
                        <option>Seleccionar ...</option>
                    </select>
                </td>
                <td colspan="3"><input id="op_lamrayadas_materia1" class="form-control op_input" type="text"/></td>
            </tr>
        </tbody>
    </table>
    <div class="col-xs-12 observaciones">Observaciones: <textarea id="observaciones_4" class="form-control textarea" name="observaciones_5" rows="1"></textarea></div>
    <!--INDICACIONES ELABORACION DE  LAMINAS RAYADAS-->
    <!--Seccion 6-->
    <table class="table table-striped">
        <tbody>
            <tr>
                <td class="td_right">Diseño</td>
                <td><input id="op_diseno" class="form-control op_input" type="text"/></td>
                <td class="td_right">Calado</td>
                <td><input id="op_calado" class="form-control op_input" type="text"/></td>
                <td class="td_right">Armado</td>
                <td><input id="op_armado" class="form-control op_input" type="text"/></td>
            </tr>
            <tr>
                <td class="td_right">Supervisó</td>
                <td><input id="op_superviso" class="form-control op_input" type="text"/></td>
                <td></td>
                <td></td>
                <td colspan="2"></td>
            </tr>
            <tr>
                <td>Suaje: Nivel Complejidad</td>
                <td colspan="5">
                   <select id="op_complejidad" class="form-control">
                       <option>Seleccionar ...</option>
                        <option>Bajo</option>
                        <option>Medio</option>
                        <option>Alto</option>
                    </select> 
                </td>
            </tr>
            <tr>
                <td class="td_right">Tiempo:</td>
                <td><input id="op_tiempo" class="form-control op_input" type="text"/></td>
                <td class="td_right">Inicio:</td>
                <td><input id="op_inicio" class="form-control op_input" type="text"/></td>
                <td class="td_right">Termino:</td>
                <td><input id="op_termino" class="form-control op_input" type="text"/></td>
            </tr>
        </tbody>
    </table>
    <!--Seccion 6-->
    <br/>
    <!--Seccion 7-->
    <table class="table table-striped">
        <tbody>
            <tr>
                <td class="td_center">PLOTERS / MUESTRA DE COLOR</td>
                <td class="td_center">MUESTRA FISICA</td>
                <td class="td_center">POSITIVO / NEGATIVO</td>
                <td class="td_center">VINIL / TIMPANO</td>
                <td class="td_center">HEMBRA Y MACHO</td>
                <td class="td_center">CONTRAS</td>
                <td class="td_center">OTRO MATERIAL</td>
            </tr>
            <tr>
                <td><input id="op_ploters_muestradecolor" class="form-control op_input" type="text"/></td>
                <td><input id="op_muestrafisica" class="form-control op_input" type="text"/></td>
                <td><input id="op_positivonegativo" class="form-control op_input" type="text"/></td>
                <td><input id="op_vinil" class="form-control op_input" type="text"/></td>
                <td><input id="op_hembramacho" class="form-control op_input" type="text"/></td>
                <td><input id="op_contras" class="form-control op_input" type="text"/></td>
                <td><input id="op_otromaterial" class="form-control op_input" type="text"/></td>
            </tr>
        </tbody>
    </table>
    <!--Seccion 7-->
</form>