<style type="text/css">
    #nuevaDireccion,#nuevoContacto,#nuevaMaquina
    {
        display: none;
    }
</style> 
<script type="text/javascript">
    $(document).ready(function()
    {
        $("#clientesG input").attr("disabled", false);
        $("#clientesG select").attr("disabled", false);
        $("#dialog-clientes").hide();
    });
</script>
<div id="dialog-clientes" title="Nuevo Cliente">

    <form  name="clientesG" id="clientesG" class="form-inline" method="POST">
        <!--div class="cos-sm-12">
            <div class="titulo_form">
                <h3>Cliente</h3>
            </div>
        </div-->
        <div class="col-sm-12 contenido_from">
            <div class="form-group col-sm-6">
                <div class="col-sm-6">
                    <label class="control-label" for="tip">Tipo Cliente:</label>
                    <select id="tipo" class="form-control" name="tipo" required>
                        <option>Seleccionar...</option>
                        <?php 
                          foreach ($this->datos as $option)
                          {
                              echo " <option value='".$option['Id_tipocliente']."'>".$option['Descripcion']."</option>";
                          }
                        ?>
                    </select>
                    <br/>
                    <label class="control-label" for="estatus">Estatus:</label>
                    <select id="Id_estatus" class="form-control" name="estatus" required>
                        <option>Seleccionar...</option>
                        <option value='10' <?php echo $selected=(@$this->clientes[0]['Id_estatus']==10)? 'selected':''; ?>>ACTIVO</option>
                        <option value="20" <?php echo $selected=(@$this->clientes[0]['Id_estatus']==20)? 'selected':''; ?>>INACTIVO</option>
                    </select>
                </div>
                <div class="col-sm-6">
                    <label class="control-label" for="nombre">Nombre</label>
                    <input id="nombre" class="form-control" name="nombre" type="nombre" value="<?php echo @$this->clientes[0]['Nombre'];?>" required>
                    <br/>
                    <label class="control-label" for="correo">Correo</label>
                    <input id="correo" class="form-control" name="correo" type="email" value="<?php echo @$this->clientes[0]['Correo'];?>">
                </div>
            </div>
            <div class="form-group col-sm-6">
                <div class="col-sm-6">
                    <label class="control-label" for="rfc">RFC</label>
                    <input id="rfc" class="form-control" name="rfc" type="text" value="<?php echo @$this->clientes[0]['RFC'];?>" required>
                    <br/>
                    <label class="control-label" for="web">Web</label>
                    <input id="web" class="form-control" name="web" type="text" value="<?php echo @$this->clientes[0]['Web'];?>">
                </div>
                <div class="col-sm-6">
                    <label class="control-label" for="tel1">Teléfono 1</label>
                    <input id="tel1" class="form-control" name="tel1" type="text" value="<?php echo @$this->clientes[0]['Telefono1'];?>">
                    <br/>
                    <label class="control-label" for="tel2">Teléfono 2</label>
                    <input id="tel2" class="form-control" name="tel2" type="text" value="<?php echo @$this->clientes[0]['Telefono2'];?>">
                    <br/>
                    <label class="control-label" for="fax">Fax</label>
                    <input id="fax" class="form-control" name="fax" type="text" value="<?php echo @$this->clientes[0]['Fax'];?>">
                </div>
            </div>
        </div>
        <button class="btn btn-primary" type="submit" id='gCliente' >Guardar Clientes</button>
    </form>
</div>
<br/>
<!-- grid de clientes -->
<button type="button" class="btn btn-success" id="btnNuevoCliente">+</button>
<table id="gridClientes"></table>
<div id="pgridClientes"></div>