<style type="text/css">
    #nuevaDireccion,#nuevoContacto,#nuevaMaquina{
        display: none;
    }
</style> 
<div id='formClientes'>
    <form  name="clientesG" id="clientesG" class="form-inline" method="POST">
        <div class="form-group col-sm-4">
            <label class="control-label col-sm-5" for="tip">Tipo Cliente:</label>
            <div class="col-sm-7">
                <select id="tipo" class="form-control" name="tipo" required>
                    <option>Seleccionar...</option>
                  <?php 
                    foreach ($this->datos as $option) {
                      echo " <option value='".$option['Id_tipocliente']."'>".$option['Descripcion']."</option>";
                    }

                  ?>
                </select>
            </div>
        </div>
        <div class="form-group col-sm-4">
            <label class="control-label col-md-5" for="estatus">Estatus:</label>
            <div class="col-md-7">
                <select id="estatus" class="form-control" name="estatus" required>
                    <option>Seleccionar...</option>
                    <option value='10' <?php echo $selected=(@$this->clientes[0]['Id_estatus']==10)? 'selected':''; ?>>ACTIVO</option>
                    <option value="20" <?php echo $selected=(@$this->clientes[0]['Id_estatus']==20)? 'selected':''; ?>>INACTIVO</option>
                </select>
            </div>
        </div>
        <div class="form-group col-sm-4">
            <label class="control-label col-md-5" for="nombre">Nombre</label>
            <div class="col-md-7">
                <input id="nombre" class="form-control" name="nombre" type="nombre" value="<?php echo @$this->clientes[0]['Nombre'];?>" required>
            </div>
        </div>
        <div class="form-group col-sm-4">
            <label class="control-label col-md-5" for="rfc">RFC</label>
            <div class="col-md-7">
                <input id="rfc" class="form-control" name="rfc" type="text" value="<?php echo @$this->clientes[0]['RFC'];?>" required>
            </div>
        </div>
        <div class="form-group col-sm-4">
            <label class="control-label col-md-5" for="tel1">Teléfono 1</label>
            <div class="col-md-7">
                <input id="tel1" class="form-control" name="tel1" type="text" value="<?php echo @$this->clientes[0]['Telefono1'];?>">
            </div>
        </div>
        <div class="form-group col-sm-4">
            <label class="control-label col-md-5" for="tel2">Teléfono 2</label>
            <div class="col-md-7">
                <input id="tel2" class="form-control" name="tel2" type="text" value="<?php echo @$this->clientes[0]['Telefono2'];?>">
            </div>
        </div>
        <div class="form-group col-sm-4">
            <label class="control-label col-md-5" for="fax">Fax</label>
            <div class="col-md-7">
                <input id="fax" class="form-control" name="fax" type="text" value="<?php echo @$this->clientes[0]['Fax'];?>">
            </div>
        </div>
        <div class="form-group col-sm-4">
            <label class="control-label col-md-5" for="correo">Correo</label>
            <div class="col-md-7">
                <input id="correo" class="form-control" name="correo" type="email" value="<?php echo @$this->clientes[0]['Correo'];?>">
            </div>
        </div>
        <div class="form-group col-sm-4">
            <label class="control-label col-md-5" for="web">Web</label>
            <div class="col-md-7">
                <input id="web" class="form-control" name="web" type="text" value="<?php echo @$this->clientes[0]['Web'];?>">
            </div>
        </div>
        <br/>
        <button class="btn btn-primary" type="submit" id='gCliente' >Guardar Clientes</button>
    </form>
</div>
<br/>
<!-- grid de clientes -->
<table id="gridClientes"></table>
<div id="pgridClientes"></div>