  <h1>error</h1>
  <h2><?php echo $this->message ?></h2>
  
  <?php if (isset($this->exception)): ?>
  
  <h3>Información:</h3>
  <p>
      <b>Mensaje de error:</b> <?php echo $this->exception->getMessage() ?>
  </p>

  <h3>Error:</h3>
  <pre><?php echo $this->exception->getTraceAsString() ?>
  </pre>

  <h3>Petición:</h3>
  <pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?>
  </pre>

  <?php endif ?>
